# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_auto_20171022_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedinusers',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='signedinusers',
            name='loggedin_ts',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='signedinusers',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
