# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20171124_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedinusers',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signedinusers',
            name='loggedin_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signedinusers',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
