# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='South Orange', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='NJ', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address_1',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address_2',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_group',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='waiver_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
