# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-15 21:44
from __future__ import unicode_literals

from django.db import migrations
import volunteermgmtdjango.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', volunteermgmtdjango.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
