# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171015_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
