# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171124_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='need_community_svc_hrs',
            field=models.BooleanField(default=False),
        ),
    ]
