# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-13 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180112_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='community_svc_hrs',
        ),
    ]
